// <auto-generated />
#nullable enable
using WebAssembly;

namespace WasmWrangler.Interop.Browser
{
	public partial class CanvasRenderingContext2D : RenderingContext
	{
		internal static new void Initialize() { JSObjectWrapperFactory.RegisterFactory(typeof(CanvasRenderingContext2D), x => new CanvasRenderingContext2D(x)); }

		internal CanvasRenderingContext2D(object obj) : base(obj) { }

		public string fillStyle
		{
			get => _js.GetObjectProperty<string>(nameof(fillStyle));
			set => _js.SetObjectProperty(nameof(fillStyle), value);
		}

		public void clearRect(int x, int y, int w, int h)
		{
			_js.Invoke(nameof(clearRect), x, y, w, h);
		}

		public void fillRect(int x, int y, int w, int h)
		{
			_js.Invoke(nameof(fillRect), x, y, w, h);
		}

		public void strokeRect(int x, int y, int w, int h)
		{
			_js.Invoke(nameof(strokeRect), x, y, w, h);
		}

	}

}
