// <auto-generated />
#nullable enable
using WebAssembly;

namespace WasmWrangler.Interop.Browser
{
	public partial class CanvasRenderingContext2D : RenderingContext
	{
		internal static void Initialize() { JSObjectWrapperFactory.RegisterFactory(typeof(CanvasRenderingContext2D), x => new CanvasRenderingContext2D(x)); }

		protected readonly JSObject _js;

		internal CanvasRenderingContext2D(object obj)
		{
			if (!(obj is JSObject))
				throw new WasmWranglerException($"Expected {nameof(obj)} to be an instance of JSObject.");

			_js = (JSObject)obj;
		}

		public string fillStyle
		{
			get => _js.GetObjectProperty<string>(nameof(fillStyle));
			set => _js.SetObjectProperty(nameof(fillStyle), value);
		}

		public void clearRect(int x, int y, int w, int h)
		{
			_js.Invoke(nameof(clearRect), x, y, w, h);
		}

		public void fillRect(int x, int y, int w, int h)
		{
			_js.Invoke(nameof(fillRect), x, y, w, h);
		}

		public void strokeRect(int x, int y, int w, int h)
		{
			_js.Invoke(nameof(strokeRect), x, y, w, h);
		}

	}

}
