// <auto-generated />
#nullable enable
using WebAssembly;

namespace WasmWrangler.Interop.Browser
{
	public partial class HTMLCanvasElement : HTMLElement
	{
		internal static new void Initialize() { JSObjectWrapperFactory.RegisterFactory(typeof(HTMLCanvasElement), x => new HTMLCanvasElement(x)); }

		internal HTMLCanvasElement(object obj) : base(obj) { }

		public int height
		{
			get => _js.GetObjectProperty<int>(nameof(height));
			set => _js.SetObjectProperty(nameof(height), value);
		}

		public int width
		{
			get => _js.GetObjectProperty<int>(nameof(width));
			set => _js.SetObjectProperty(nameof(width), value);
		}

		public T? getContext<T>(string contextId, object? options = null)
			where T: RenderingContext
		{
			var result = _js.Invoke(nameof(getContext), contextId, options);

			if (result == null)
				return null;

			return JSObjectWrapperFactory.Create<T>(result);
		}

	}

}
