// <auto-generated />
#nullable enable
using WebAssembly;

namespace WasmWrangler.Interop.Browser
{
	public partial class HTMLElement
	{
		internal static void Initialize() { JSObjectWrapperFactory.RegisterFactory(typeof(HTMLElement), x => new HTMLElement(x)); }

		protected readonly JSObject _js;

		internal HTMLElement(object obj)
		{
			if (!(obj is JSObject))
				throw new WasmWranglerException($"Expected {nameof(obj)} to be an instance of JSObject.");

			_js = (JSObject)obj;
		}

		public string innerText
		{
			get => _js.GetObjectProperty<string>(nameof(innerText));
			set => _js.SetObjectProperty(nameof(innerText), value);
		}

		private CSSStyleDeclaration? _style;

		public CSSStyleDeclaration style
		{
			get => _style ?? (_style = new CSSStyleDeclaration(_js.GetObjectProperty<JSObject>(nameof(style))));
		}

	}

}
