// <auto-generated />
#nullable enable
using WebAssembly;

namespace WasmWrangler.Interop.Browser
{
	public partial class HTMLCanvas : HTMLElement
	{
		internal static new void Initialize() { JSObjectWrapperFactory.RegisterFactory(typeof(HTMLCanvas), x => new HTMLCanvas(x)); }

		internal HTMLCanvas(object obj) : base(obj) { }

	}

}
