// <auto-generated />
#nullable enable
using WebAssembly;

namespace WasmWrangler.Interop.Browser
{
	public partial class RenderingContext
	{
		internal static void Initialize() { JSObjectWrapperFactory.RegisterFactory(typeof(RenderingContext), x => new RenderingContext(x)); }

		protected readonly JSObject _js;

		internal RenderingContext(object obj)
		{
			if (!(obj is JSObject))
				throw new WasmWranglerException($"Expected {nameof(obj)} to be an instance of JSObject.");

			_js = (JSObject)obj;
		}

	}

}
