// <auto-generated />
#nullable enable
namespace WasmWrangler.Interop.Browser
{
	public static class WasmWranglerAssemblyInitializer
	{
		public static void Initialize()
		{
			WasmWrangler.Interop.Browser.CSSStyleDeclaration.Initialize();
			WasmWrangler.Interop.Browser.HTMLCanvas.Initialize();
			WasmWrangler.Interop.Browser.HTMLElement.Initialize();
		}
	}
}

