// <auto-generated />
#nullable enable
using WebAssembly;
namespace WasmWrangler
{
	public partial class console
	{
		private readonly JSObject _js;

		public console(JSObject js)
		{
			_js = js;
		}

		public static console? Wrap(JSObject? js) => js != null ? new console(js) : null;

		public static implicit operator JSObject(console obj) => obj._js;

	}

	public partial class document
	{
		private readonly JSObject _js;

		public document(JSObject js)
		{
			_js = js;
		}

		public static document? Wrap(JSObject? js) => js != null ? new document(js) : null;

		public static implicit operator JSObject(document obj) => obj._js;

	}

}
