// <auto-generated />
#nullable enable
using WebAssembly;
namespace WasmWrangler
{
	public partial class HTMLElement
	{
		private readonly JSObject _js;

		internal HTMLElement(object obj)
		{
			if (!(obj is JSObject))
				throw new WasmWranglerException($"Expected {nameof(obj)} to be an instance of JSObject.");

			_js = (JSObject)obj;
		}

		public string innerText
		{
			get => _js.GetObjectProperty<string>(nameof(innerText));
			set => _js.SetObjectProperty(nameof(innerText), value);
		}
		public JSObject style
		{
			get => _js.GetObjectProperty<JSObject>(nameof(style));
		}
	}

	public static partial class JS
	{
		public static partial class console
		{
			private static JSObject? __js;

			private static JSObject _js
			{
				get
				{
					if (__js == null)
						__js = (JSObject)Runtime.GetGlobalObject(nameof(console));

					return __js;
				}
			}

			public static void dir(object? item = null, object? options = null)
			{
				_js.Invoke(nameof(dir), item, options);
			}

			public static void info(params object[] data)
			{
				_js.Invoke(nameof(info), data);
			}

		}
	}

	public static partial class JS
	{
		public static partial class document
		{
			private static JSObject? __js;

			private static JSObject _js
			{
				get
				{
					if (__js == null)
						__js = (JSObject)Runtime.GetGlobalObject(nameof(document));

					return __js;
				}
			}

			public static HTMLElement? getElementById(string element)
			{
				var result = _js.Invoke(nameof(getElementById), element);

				if (result == null)
					return null;

				return new HTMLElement(result);
			}

		}
	}

}
