// <auto-generated />
#nullable enable
using WebAssembly;

namespace WasmWrangler
{
	public partial class HTMLElement
	{
		private readonly JSObject _js;

		public HTMLElement(JSObject js)
		{
			_js = js;
		}

		public static HTMLElement? Wrap(JSObject? js) => js != null ? new HTMLElement(js) : null;

        public static explicit operator HTMLElement(JSObject js) => new HTMLElement(js);

        public static explicit operator JSObject(HTMLElement obj) => obj._js;

		public string innerText
		{
			get => _js.GetObjectProperty<string>(nameof(innerText));
			set => _js.SetObjectProperty(nameof(innerText), value);
		}
		public JSObject style
		{
			get => _js.GetObjectProperty<JSObject>(nameof(style));
		}
	}
}
