name: CI

on:
  push:
    paths-ignore:
    - '.github/workflows/release.yml'
    - 'assets/**'
    - 'docs/**'
    - 'Readme.md'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Get Wasm SDK
      run: dotnet msbuild build\WasmEnsureSDKAvailable.proj -nologo

    - name: Restore
      run: |
        dotnet msbuild build\Build.proj -nologo -v:n -t:Restore
        dotnet tool install -g libman
        cd ext
        libman restore
        cd ..

    - name: Build
      run: dotnet msbuild build\Build.proj -nologo -v:n -t:Build

    - name: Test
      run: dotnet msbuild build\Build.proj -nologo -v:n -t:Test  
