name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Get Wasm SDK
      run: dotnet msbuild build\WasmEnsureSDKAvailable.proj -nologo

    - name: Restore
      run: dotnet msbuild build\Build.proj -nologo -v:n -t:Restore

    - name: Release
      run: -
        nuget setApiKey ${{ secrets.NUGET_API_KEY }}
        dotnet msbuild build\Build.proj -nologo -v:n -t:Release
